### PR TITLE
fix: add compilation info cache to SbtProcess for consistent warning display

### LINKED ISSUE #1144: Warning disapear after rerunning code.
### Describe the bug

After rerunning, the warning disappears. Exactly the same thing happens when re-entering the snippet link.

### Scastie snippet link

https://scastie.scala-lang.org/0IXp54QcQUmcy8V02yJsgA

### To Reproduce

Code:
`@main def main = {
  Nil match {
    case Seq(xs*) => println("test")
  }
}
`
Run twice.

### Expected behavior

The warning does not disappear.

### Screenshot ( Optional )

_No response_

### Version

Scastie website

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by warcholjakub**
# Fixes #1144
## Summary
This PR adds a cache for compilation warnings in SbtProcess, ensuring users consistently see relevant warnings even when SBT returns cached results without warnings.
## Key changes
- Store compilation warnings and input hash in SbtProcess.
- Reuse cached warnings when SBT returns cached results without warnings.
- Ensure warning reporting is consistent for unchanged code.

### CODE REVIEW

File: sbt-runner/src/main/scala/org/scastie/sbt/SbtProcess.scala [hunk 1]
```diff
@@ -24,14 +24,31 @@ object SbtProcess {
 
   sealed trait Data
   case class SbtData(currentInputs: SbtInputs) extends Data
+
+  case class CompilationInfoCache(
```
Comment (rochala) [inline sbt-runner/src/main/scala/org/scastie/sbt/SbtProcess.scala]: This will grow indefinitely, our runners can run for few weeks, I'm scared that it may use too much memory. You should adjust it so it is expiring cache (e.g provided by guava)

File: balancer/src/test/scala/org/scastie/balancer/DispatchActorIntegrationTest.scala [hunk 2]
```diff
@@ -25,6 +25,46 @@ class LoadBalancerRecoveryTest()
...
+    /* First run - execute code and generate warnings */
+    val sid = run(code)
+
+    waitFor(sid, Map(sid -> code))(p =>
+      p.isDone && p.compilationInfos.nonEmpty
+    )
+
+    /* Second run - re-run the same snippet */
+    val wrapped =
+      s"""|object Main {
```
Comment (rochala) [inline balancer/src/test/scala/org/scastie/balancer/DispatchActorIntegrationTest.scala]: How can I be sure that this is the same snippet ?

Comment (warcholjakub) [reply balancer/src/test/scala/org/scastie/balancer/DispatchActorIntegrationTest.scala]: Anyhow, I changed it, and now it fetches the snippet after the first compilation.
